# Netlify configuration for NXTRIX Landing Page - JavaScript ONLY
[build]
  # Functions for API endpoints
  functions = "./functions"
  publish = "."
  command = "npm install --production --ignore-engines && echo 'JavaScript-only build complete'"
  ignore = "requirements.txt,streamlit-deps.txt,*.py,.streamlit/,streamlit.toml,runtime.txt,app.json,.buildpacks,.streamlitignore"
  
[build.environment]
  # Environment variables - JavaScript/Node.js only
  NODE_ENV = "production"
  NODE_VERSION = "18"
  # Explicitly disable Python
  PYTHON_VERSION = ""
  # Force JavaScript-only build
  SKIP_PYTHON_INSTALL = "true"
  # Disable Python detection
  DISABLE_PYTHON_BUILD = "true"

# API redirects  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect rules
[[redirects]]
  # Redirect /app/* to the main software when public launch happens
  from = "/app/*"
  to = "https://app.nxtrix.com/:splat"
  status = 302
  force = false
  
[[redirects]]
  # Catch-all for SPA behavior (if needed)
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://cdn.emailjs.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.railway.app https://*.heroku.com https://*.supabase.co https://cdn.jsdelivr.net; img-src 'self' data: https:;"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling and build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true
